# Generated by Django 4.2.5 on 2023-10-08 15:17

import api.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('sale_type', models.CharField(choices=[('Sale', 'For Sale'), ('Rent', 'For Rent')], default='Sale', max_length=50, verbose_name='action')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Price')),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Bedrooms')),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Bathrooms')),
                ('home_type', models.CharField(blank=True, choices=[('Apartment', 'Apartment'), ('Villa', 'Villa'), ('Commercial', 'Commercial'), ('Project', 'Project'), ('Land', 'Land')], max_length=50, null=True, verbose_name='Home Type')),
                ('square_fit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Square Feet')),
                ('object_id', models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Object ID')),
                ('photo_main', models.ImageField(blank=True, null=True, upload_to=api.models.upload_to, verbose_name='Main Photo')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('list_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Publication Date')),
                ('building_year', models.CharField(blank=True, max_length=4, null=True, verbose_name='Year Built')),
                ('best_offer', models.BooleanField(default=False, verbose_name='Best Offer')),
                ('modx_id', models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='ID in MODX Database')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.area', verbose_name='Area')),
                ('city', models.ManyToManyField(blank=True, null=True, to='api.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Object',
                'verbose_name_plural': 'Objects',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=api.models.upload_to)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.property')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.city'),
        ),
    ]
